export const boards = [
    {
      squares: [
        { text: 'Go', image: 'go.jpg' },
        { text: '#1', image: 'cinema.jpg' },
        { text: '#2', image: 'question.jpg' },
        { text: '#3', image: 'water.jpg' },
        { text: '#4', image: 'visa.jpg' },
        { text: '#5', image: 'electric.jpg' },
        { text: '#6', image: 'chest3.webp' },
        { text: '#7', image: 'question2.jpg' },
        { text: '#8', image: 'cf-serenity.jpg' },
        { text: '#9', image: 'cf-serenity.jpg' },
        { text: '#10', image: 'navidad.jpg' },
        { text: '#11', image: 'jewelry.png' },
        { text: '#12', image: 'tax.jpg' },
        { text: '#13', image: 'cinema.jpg' },
        { text: '#14', image: 'cloth.jpg' },
        { text: 'Jail', image: 'question1.jpg' },
      ],
      questionIndices: [2, 7, 15],
    },
    {
      squares: [
        { text: 'Go', image: 'go.jpg' },
        { text: '#1', image: 'tax.jpg' },
        { text: '#2', image: 'cf-classic.jpg' },
        { text: '#3', image: 'question.jpg' },
        { text: 'Jail', image: 'rent.jpg' },
        { text: '#5', image: 'cinema.jpg' },
        { text: '#6', image: 'cloth.jpg' },
        { text: '#7', image: 'question2.jpg' },
        { text: '#8', image: 'bd-mom.webp' },
        { text: '#9', image: 'electric.jpg' },
        { text: '#10', image: 'cf-classic.jpg' },
        { text: '#11', image: 'alquilar.webp' },
        { text: '#12', image: 'water.jpg' },
        { text: '#13', image: 'question.jpg' },
        { text: '#14', image: 'chest.webp' },
        { text: '#15', image: 'study.jpg' },
      ],
      questionIndices: [3, 7, 13],
    },
    {
      squares: [
        { text: 'Go', image: 'go.jpg' },
        { text: '#1', image: 'water.jpg' },
        { text: '#2', image: 'cf-grow.jpg' },
        { text: '#3', image: 'question.jpg' },
        { text: '#4', image: 'health.jpg' },
        { text: '#5', image: 'question2.jpg' },
        { text: '#6', image: 'chest3.webp' },
        { text: '#7', image: 'electric.jpg' },
        { text: '#8', image: 'bd-son.jpg' },
        { text: '#9', image: 'cinema.jpg' },
        { text: '#10', image: 'cloth.jpg' },
        { text: '#11', image: 'bienes.jpg' },
        { text: '#12', image: 'question.jpg' },
        { text: '#13', image: 'cf-grow.jpg' },
        { text: '#14', image: 'tax.jpg' },
        { text: 'Jail', image: 'hijos.jpg' },
      ],
      questionIndices: [3, 5, 12],
    },
];
