export const boards = [
    {
      squares: [
        { text: 'Go', image: null },
        { text: '#1', image: null },
        { text: '#2', image: 'question.jpg' },
        { text: '#3', image: 'water.jpg' },
        { text: '#4', image: null },
        { text: '#5', image: 'electric.jpg' },
        { text: '#6', image: 'chest3.webp' },
        { text: '#7', image: 'question2.jpg' },
        { text: '#8', image: 'cf.png' },
        { text: '#9', image: 'cf.png' },
        { text: '#10', image: 'luxur.webp' },
        { text: '#11', image: null },
        { text: '#12', image: 'tax.png' },
        { text: '#13', image: null },
        { text: '#14', image: null },
        { text: 'Jail', image: null },
      ],
      questionIndices: [2, 7],
    },
    {
      squares: [
        { text: 'Go', image: null },
        { text: '#1', image: 'tax.png' },
        { text: '#2', image: 'cf.png' },
        { text: '#3', image: 'question.jpg' },
        { text: 'Jail', image: null },
        { text: '#5', image: null },
        { text: '#6', image: null },
        { text: '#7', image: 'question2.jpg' },
        { text: '#8', image: 'luxur.webp' },
        { text: '#9', image: 'electric.jpg' },
        { text: '#10', image: 'cf.png' },
        { text: '#11', image: null },
        { text: '#12', image: 'water.jpg' },
        { text: '#13', image: 'question.jpg' },
        { text: '#14', image: 'chest.webp' },
        { text: '#15', image: null },
      ],
      questionIndices: [3, 7, 13],
    },
    {
      squares: [
        { text: 'Go', image: null },
        { text: '#1', image: 'water.jpg' },
        { text: '#2', image: 'cf.png' },
        { text: '#3', image: 'question.jpg' },
        { text: '#4', image: null },
        { text: '#5', image: 'question2.jpg' },
        { text: '#6', image: 'chest3.webp' },
        { text: '#7', image: 'electric.jpg' },
        { text: '#8', image: 'luxur.webp' },
        { text: '#9', image: null },
        { text: '#10', image: 'question3.jpg' },
        { text: '#11', image: null },
        { text: '#12', image: 'question.jpg' },
        { text: '#13', image: 'cf.png' },
        { text: '#14', image: 'tax.png' },
        { text: 'Jail', image: null },
      ],
      questionIndices: [3,5, 10, 12],
    },
];
